import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import { bodyFor, claudeAssets, syncClaudeAssets } from "../plugins/harness-core/lib/claude-assets.mjs";
import { bin, makeRepo, runTool } from "./helpers.mjs";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");

// THE VANILLA INTEGRATION, and the one thing that makes it safe. Copying the drills into a target's
// `.claude/` is what lets a repository use them with no install step — and copies are exactly how
// this project's own agents fell eleven lines behind in another repository. The copies are therefore
// generated, banner-marked, and gated; these cases defend that, not the copying.
//
// The failures worth planting are the silent ones: a banner that lands above the front matter (the
// skill stops existing, with no error), a drifted copy reported as if it were merely absent, and an
// agent that ships to adopters but never reaches the target.

test("every skill and agent the plugins carry is offered to a target", () => {
  // A LIST WOULD BE A SECOND PLACE TO REMEMBER SOMETHING. The entry nobody adds is invisible until
  // somebody needs exactly that agent, so the set is walked from the plugin tree rather than named.
  const dests = claudeAssets(REPO).map((a) => a.dest.split("\\").join("/"));
  for (const plugin of readdirSync(join(REPO, "plugins"))) {
    const agents = join(REPO, "plugins", plugin, "agents");
    if (!existsSync(agents)) continue;
    for (const f of readdirSync(agents).filter((n) => n.endsWith(".md"))) {
      assert.ok(dests.includes(`.claude/agents/${f}`), `${plugin}'s ${f} ships to adopters but never reaches a target`);
    }
  }
  assert.ok(dests.some((d) => d.endsWith("/SKILL.md")), "skills must travel too, not only agents");
});

test("the banner goes AFTER the front matter, never before it", () => {
  // Claude Code parses `---` at byte zero. A comment above it makes the block invisible, so the
  // skill loses its name and description — a failure that looks like the skill not existing at all,
  // with nothing in any log to say why.
  for (const asset of claudeAssets(REPO)) {
    if (!asset.source.endsWith(".md")) continue;
    const raw = readFileSync(asset.abs, "utf8");
    if (!raw.startsWith("---\n")) continue;
    const body = bodyFor(asset);
    assert.ok(body.startsWith("---\n"), `${asset.dest} must still open with its front matter`);
    const end = body.indexOf("\n---\n") + 5;
    assert.match(body.slice(end, end + 200), /GENERATED by harness-claude-sync/, `${asset.dest} must carry the banner directly after the front matter`);
  }
});

test("the banner names the source file it came from", () => {
  // "Do not edit" without saying where to edit instead sends somebody hunting, and the likeliest
  // outcome of a failed hunt is that they edit the copy anyway.
  const asset = claudeAssets(REPO).find((a) => a.dest.endsWith("decomposer.md"));
  assert.ok(asset, "the decomposer is the canary — if it stops travelling, the walk broke");
  assert.match(bodyFor(asset), /plugins\/harness-gates\/agents\/decomposer\.md/);
});

test("a fresh target receives the drills, and a second run is a no-op", () => {
  const target = makeRepo({});
  const first = syncClaudeAssets(REPO, target);
  assert.ok(first.wrote.length > 10, "a fresh target must receive the whole set");
  assert.equal(first.drifted.length, 0, "nothing can have drifted in a repo with no copies");
  assert.deepEqual(syncClaudeAssets(REPO, target).wrote, [], "a sync that keeps writing is one nobody can trust as a check");
});

test("drift and absence are reported apart, because only one of them is a mistake", () => {
  // Absent is a repo that has not synced yet — routine. Drifted is a repo where somebody edited the
  // generated artifact instead of the source, which is the exact failure this mechanism exists to
  // prevent. Reporting them the same way would hide the one worth seeing.
  const target = makeRepo({});
  syncClaudeAssets(REPO, target);
  const edited = join(target, ".claude/agents/decomposer.md");
  writeFileSync(edited, `${readFileSync(edited, "utf8")}\nlocally tweaked\n`);
  const gone = join(target, ".claude/skills/decompose/SKILL.md");
  writeFileSync(gone, "");

  const { drifted, missing } = syncClaudeAssets(REPO, target, { check: true });
  assert.ok(drifted.some((f) => f.endsWith("decomposer.md")), "a hand-edited copy must read as drift");
  assert.ok(drifted.some((f) => f.endsWith("SKILL.md")), "an emptied copy is drift, not absence");
  assert.equal(missing.length, 0, "nothing is absent here — every file exists");
});

test("--check writes nothing, so it is safe to run in CI on a read-only checkout", () => {
  const target = makeRepo({});
  const { wrote } = syncClaudeAssets(REPO, target, { check: true });
  assert.deepEqual(wrote, []);
  assert.ok(!existsSync(join(target, ".claude/agents")), "check mode must not create the tree it is checking");
});

test("the launcher fails on drift and passes once synced", () => {
  // Run the real executable: the gate is only worth anything if its exit status is right, and a
  // module-level test cannot see the exit status.
  const target = makeRepo({});
  const red = runTool(bin("harness-core", "harness-claude-sync"), target, ["--check"]);
  assert.equal(red.code, 1, "an unsynced repo must fail the gate");
  assert.match(red.out, /missing/, "and it must say which files");

  assert.equal(runTool(bin("harness-core", "harness-claude-sync"), target, []).code, 0);
  const green = runTool(bin("harness-core", "harness-claude-sync"), target, ["--check"]);
  assert.equal(green.code, 0, green.out);
});

test("a skill's extra files travel with it, not just SKILL.md", () => {
  // A skill may carry references alongside its SKILL.md, and a sync that took only the entry point
  // would deliver a drill whose own citations 404 — worse than not delivering it.
  const target = makeRepo({});
  mkdirSync(join(target, "probe"), { recursive: true });
  const withRefs = claudeAssets(REPO).filter((a) => a.dest.includes("/skills/") && !a.dest.endsWith("SKILL.md"));
  if (withRefs.length === 0) return; // no multi-file skill ships today; the walk is still recursive
  syncClaudeAssets(REPO, target);
  for (const a of withRefs) assert.ok(existsSync(join(target, a.dest)), `${a.dest} did not travel`);
});
