import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import { binMap, launchers } from "../scripts/sync-launchers.mjs";

// Shellcheck, in the suite rather than only in CI.
//
// A backtick-quoted skill name inside a double-quoted shell string reads as command substitution.
// `npm test` was green; CI caught it; the round trip cost a push, a runner, and a red PR — for a
// check that was already installed on this machine and takes 200ms.
//
// The rule this enforces on the harness itself: every check CI runs should be runnable locally by
// the project's own command. A verification step that only exists in CI turns a typo into a
// commit-push-wait cycle, and the wait is where people stop verifying.
const PLUGINS = join(dirname(fileURLToPath(import.meta.url)), "../plugins");
const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");

const filesIn = (dir) => {
  try {
    return readdirSync(dir).map((f) => join(dir, f));
  } catch {
    return []; // a plugin need not ship launchers, or hooks
  }
};

/**
 * Every shell script this harness SHIPS — launchers and the git-hook templates alike.
 *
 * CI shellchecks `plugins/*<!---->/bin/*`, which is every launcher and no hook. The hooks run on
 * every commit and every push in an adopter's repository, and they had never been checked by
 * anything: `pre-commit` word-split its staged-file list, so a filename containing a space silently
 * skipped formatting and then handed `git add` two paths that do not exist. A glob is an
 * enumeration, and an enumeration only ever covers what its author thought of.
 */
// `.cmd` twins are BATCH, not shell — generated by scripts/sync-launchers.mjs and deliberately
// CRLF, which shellcheck reports as SC1017 before it gets as far as noticing the file is not shell
// at all. Filtering them here is the fix; making them LF to satisfy shellcheck would break them on
// the only platform they exist for.
const isShell = (f) => !f.endsWith(".cmd");

const shipped = () => [
  ...readdirSync(PLUGINS, { withFileTypes: true })
    .filter((p) => p.isDirectory())
    .flatMap((p) => filesIn(join(PLUGINS, p.name, "bin")).filter(isShell)),
  ...filesIn(join(PLUGINS, "harness-core/templates/husky")),
];

const available = () => {
  try {
    execFileSync("shellcheck", ["--version"], { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
};

test("every shipped shell script passes shellcheck", () => {
  const files = shipped();
  assert.ok(files.length > 0, "no scripts found — the glob is wrong, not the repo");
  assert.ok(
    files.some((f) => /[\\/]husky[\\/]/.test(f)),
    "the git hooks must be in scope — they run on every commit in an adopter's repo",
  );
  if (!available()) {
    // Says so rather than passing silently. CI installs shellcheck, so the dimension is always
    // measured somewhere — a local skip is a convenience, never a verdict.
    console.error("shellcheck not installed locally — skipped here; CI still enforces it.");
    return;
  }
  try {
    execFileSync("shellcheck", files, { stdio: "pipe" });
  } catch (err) {
    assert.fail(`shellcheck reported problems:\n\n${err.stdout ?? ""}${err.stderr ?? ""}`);
  }
});

test("CI does not keep a second list of what to shellcheck", () => {
  // The workflow used to re-glob `plugins/*/bin/*` itself. That was a SECOND list of the same
  // thing, and the two drifted the moment the .cmd twins arrived — the test excluded them, the
  // workflow did not, and CI failed on batch files for not being shell.
  //
  // Two lists of one thing do not stay equal. They stay equal until the first change, and then one
  // of them is wrong and nobody knows which. The list lives here, where the reasoning for what is
  // in it lives; CI installs the tool and runs the suite.
  const wf = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../.github/workflows/pipeline.yml"), "utf8");
  assert.doesNotMatch(wf, /^\s*shellcheck\s+\S/m, "CI is globbing for shellcheck again — the scope belongs in this file, not two places");
  assert.match(wf, /install -y -qq shellcheck/, "CI must still install it, or this whole dimension silently skips");
});

test("every launcher is executable, and that is structural rather than lucky", () => {
  // Found the expensive way: one launcher shipped without its execute bit and every invocation of it
  // died with "permission denied" — caught only because a portability case happened to run that one
  // through the shell rather than importing the module. Every other launcher is 755 by luck of how
  // it was created, which is not a property, it is a coincidence that has held so far.
  //
  // git tracks exactly one permission bit, so this is also what a fresh clone gets. The .cmd twins
  // are deliberately NOT checked: Windows does not have a mode, and asserting one there would be
  // testing the checkout rather than the file.
  const mode = (p) => statSync(p).mode & 0o777;
  let checked = 0;
  for (const plugin of readdirSync(PLUGINS)) {
    const dir = join(PLUGINS, plugin, "bin");
    if (!existsSync(dir)) continue;
    for (const name of readdirSync(dir).filter((f) => !f.endsWith(".cmd"))) {
      const file = join(dir, name);
      assert.ok(mode(file) & 0o100, `${plugin}/bin/${name} is not executable by its owner (${mode(file).toString(8)})`);
      assert.ok(mode(file) & 0o001, `${plugin}/bin/${name} is not executable by others (${mode(file).toString(8)}) — a clone would inherit that`);
      checked++;
    }
  }
  assert.ok(checked > 20, `only ${checked} launchers checked — this stopped looking at most of them`);
});

// ── installable as a dependency ───────────────────────────────────────────────
//
// The container pulls a repository in and works on it here, but that repository's OWN CI has no
// `/plugin install` and no CLAUDE_PLUGIN_ROOT. A git dependency is how the central gates reach it,
// and these are the properties that make that work rather than appear to.

test("every launcher is a package bin, and the map is generated rather than remembered", () => {
  const pkg = JSON.parse(readFileSync(join(REPO, "package.json"), "utf8"));
  const want = binMap(launchers());
  assert.deepEqual(pkg.bin, want, "run `node scripts/sync-launchers.mjs` — a command missing from `bin` vanishes on install");
  assert.equal(Object.keys(pkg.bin).length, launchers().length, "one bin entry per launcher, no more and no fewer");
});

test("a bin entry points at the MODULE, because npm's .bin is a symlink", () => {
  // THE TRAP THIS AVOIDS. npm links node_modules/.bin/<name> → the target. The shell launchers
  // resolve $0's directory and look for `../lib/<module>.mjs`, which under that symlink resolves to
  // `node_modules/lib` — absent. Node resolves a module's relative imports from its REAL path, so
  // linking the module directly is immune. Nothing about this fails loudly: the gate is simply not
  // there, in somebody else's CI, which is where nobody is watching.
  const pkg = JSON.parse(readFileSync(join(REPO, "package.json"), "utf8"));
  for (const [name, target] of Object.entries(pkg.bin)) {
    const isShellProgram = launchers().find((l) => l.name === name)?.module === null;
    if (isShellProgram) {
      assert.match(target, /\/bin\//, `${name} is a shell program and must link to its script`);
      continue;
    }
    assert.match(target, /\/lib\/[\w.-]+\.mjs$/, `${name} must link to its module, not to the shell launcher`);
    assert.ok(existsSync(join(REPO, target)), `${name} points at ${target}, which does not exist`);
  }
});

test("everything a bin points at is directly executable — it carries a shebang", () => {
  // A module linked into .bin is run by the OS, not by `node <path>`. Without the shebang the
  // symlink is an unrunnable text file, and the error names a shell syntax error in JavaScript.
  const pkg = JSON.parse(readFileSync(join(REPO, "package.json"), "utf8"));
  for (const target of Object.values(pkg.bin)) {
    const first = readFileSync(join(REPO, target), "utf8").split("\n")[0];
    assert.match(first, /^#!/, `${target} is linked into .bin but has no shebang`);
    // The exec bit, for the same reason the launchers have one and a banked idea made it
    // structural there: committed 644, the symlink is unrunnable and every invocation is
    // "Permission denied" — on a machine that is not this one.
    assert.ok(statSync(join(REPO, target)).mode & 0o111, `${target} is linked into .bin but is not executable`);
  }
});

test("the published package carries the plugins and none of this repository's own state", () => {
  // An adopter installing the harness must not receive OUR budgets, OUR tests or OUR web app —
  // that is the one rule this whole repository runs on, at the point where it would travel.
  const pkg = JSON.parse(readFileSync(join(REPO, "package.json"), "utf8"));
  assert.ok(Array.isArray(pkg.files) && pkg.files.length, "an unset `files` ships the entire checkout");
  assert.ok(pkg.files.some((f) => f.startsWith("plugins")), "the plugins are the product");
  for (const ours of ["tests", "web", "arch-budget.json", "docs"]) {
    assert.ok(!pkg.files.includes(ours), `${ours} is this repository's own state and must not ship`);
  }
});
