// THE SYNTHESIZER — a projen project type that writes the harness into a consuming repository.
//
// WHY projen AT ALL, given the bootstrap already writes these files. Because the bootstrap writes them
// exactly once. `put()` skips any file that exists, which is right for a file somebody customised and
// wrong for one that is merely old, and nothing can tell those apart (idea #29). projen deletes the
// question rather than answering it: you never customise the artifact, you customise the generator, and
// regeneration is the update path.
//
// WHAT WE TAKE FROM IT, AND WHAT WE REFUSE.
//
// Taken: the synthesis engine, component inheritance, and the override API.
//
// Refused, and measured rather than assumed (docs/adr/0001):
//   · THE TASK RUNNER. Routing scripts through projen Tasks costs +590ms on EVERY command — 456ms for
//     `biome check` becomes 1043ms — a constant tax that is 2.3x on a fast lint and lands squarely on
//     the inner loop. Writing the real command into package.json instead measured 263ms. So components
//     emit plain npm scripts, and package.json stays readable as itself.
//   · THE BATTERIES. TypeScriptProject ships jest, eslint and prettier. Adopting them would move a
//     consumer OFF biome and rstest, reversing the toolchain and trading one dependency for two.
//   · THE RELEASE. projen wrote `version: 0.0.0` over a real 1.129.0 until `release: false`. The
//     consumer's semantic-release owns its version; we do not.
//
// TWO FILE CLASSES, and the distinction is the whole shape/content split:
//   · GENERATED — rewritten every synth, content belongs upstream. `harness.json` is one.
//   · SEEDED — written once, NEVER clobbered, content belongs to the repo. Budgets, IDEAS.md,
//     LESSONS.md. The harness owns their SHAPE and validates it; it must never own what is in them.
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Component, JsonFile, SampleFile, TextFile, typescript } from "projen";
import { renderRstest } from "../plugins/harness-core/lib/configs.mjs";
import { BIOME_SCRIPTS, GATE_SCRIPTS } from "../plugins/harness-core/lib/scripts.mjs";
import { DEFAULTS } from "../plugins/harness-gates/lib/descriptor.mjs";
import { lockedViolations } from "../plugins/harness-gates/lib/sanitation.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const template = (p) => readFileSync(join(HERE, "../plugins/harness-core/templates", p), "utf8");

/** The npm package a consuming repository installs to get the gates on `node_modules/.bin`. */
export const HARNESS_PACKAGE = "@ejclark/dungeon-crawler";

/** Descriptor keys a consumer may set. Anything absent takes the documented default — never inference. */
const DESCRIPTOR_KEYS = Object.keys(DEFAULTS);

// Re-exported, never redefined. Both delivery paths name the same six commands, and the gate that
// catches a second copy of them is one of the six.
export { GATE_SCRIPTS };

/**
 * Emits `harness.json` — the capability descriptor every scanner reads.
 *
 * ONLY NON-DEFAULT KEYS ARE WRITTEN, and no file at all when a repo is entirely conventional. That is
 * `DESCRIPTOR.md`'s promise kept ("a conventional TypeScript project needs no file at all") rather than
 * restated: a descriptor listing six values identical to the defaults reads like six decisions somebody
 * made, and the next person to change a default would have to hunt them all down.
 *
 * This is a GENERATED file. It exists because the same values already live in `.projenrc.ts`, and two
 * hand-maintained copies of one truth is the drift this repository has a suite devoted to preventing.
 */
export class GatesComponent extends Component {
  constructor(project, options = {}) {
    super(project, "harness-gates");

    const declared = Object.fromEntries(
      DESCRIPTOR_KEYS.filter((k) => options[k] !== undefined && !same(options[k], DEFAULTS[k])).map((k) => [
        k,
        options[k],
      ]),
    );

    if (Object.keys(declared).length > 0) {
      new JsonFile(project, "harness.json", {
        obj: declared,
        marker: false, // a JSON descriptor read by six scanners; a "generated by" key is not schema
        readonly: true,
      });
    }

    project.addDevDeps(HARNESS_PACKAGE);
    for (const [name, exec] of Object.entries(GATE_SCRIPTS)) {
      project.package.setScript(name, exec);
    }
  }
}

/** Structural equality, good enough for descriptor values (strings and flat string arrays). */
function same(a, b) {
  return JSON.stringify(a) === JSON.stringify(b);
}

/**
 * Biome — lint and format, one tool and one config file.
 *
 * projen ships no Biome component (projen/projen#3966, open since Nov 2024), so this is written here
 * and is upstreamable once it has earned it. The config itself is NOT restated: it is the same
 * `templates/node/biome.json` the bootstrap path already writes, read rather than copied, so the two
 * delivery paths cannot drift while both exist.
 *
 * Biome replaces eslint AND prettier — which is why `HarnessProject` turns both off. Two linters
 * disagreeing about one file is worse than either alone.
 */
export class BiomeComponent extends Component {
  constructor(project, options = {}) {
    super(project, "harness-biome");
    // A JsonFile, NOT a TextFile, and the difference is load-bearing rather than stylistic.
    // `addOverride` — the escape hatch this design promises — only works on an ObjectFile, so a
    // templated TextFile would have made biome.json the one config a consumer could not adjust
    // without replacing wholesale. It also means SanitationComponent sees the MERGED result at
    // synth, which is the only point where a consumer's override is visible.
    //
    // The cost is that the emitted file is re-serialised rather than byte-identical to the template.
    // That is fine: the property worth defending is that both delivery paths carry the same config,
    // and semantic equality says that better than a byte comparison ever did.
    new JsonFile(project, "biome.json", {
      obj: JSON.parse(template("node/biome.json")),
      readonly: true,
      marker: false, // JSON has no comment syntax; a marker key would not be schema
    });
    project.addDevDeps(`@biomejs/biome@${options.biomeVersion ?? "^2.5.6"}`);
    for (const [name, exec] of Object.entries(BIOME_SCRIPTS)) project.package.setScript(name, exec);
    project.addVerifyStep("npm run lint");
  }
}

/**
 * rstest — the test runner, scoped by the descriptor.
 *
 * Also has no projen component. The config is RENDERED from `testDir`/`specSuffix` rather than
 * templated, because a runner pointed at a glob that matches nothing collects zero tests and reports
 * a green suite. That is the exact false green the gates exist to prevent, produced by the harness's
 * own scaffolding — and it has already happened twice here at one layer down (see `configs.mjs`).
 */
export class RstestComponent extends Component {
  constructor(project, options = {}) {
    super(project, "harness-rstest");
    new TextFile(project, "rstest.config.ts", {
      lines: renderRstest(project.descriptor).split("\n"),
      readonly: true,
      marker: false, // the rendered file carries its own "edit .projenrc.ts" line
    });
    project.addDevDeps(`@rstest/core@${options.rstestVersion ?? "^0.11.4"}`);
    project.package.setScript("test", "rstest run");
    project.package.setScript("test:watch", "rstest watch");
    project.addVerifyStep("npm test");
  }
}

/**
 * The shape of `docs/LESSONS.md`, which is the worked example of a contextual system.
 *
 * These field names are already the file's own documented format and are already parsed by
 * `harness-incident-scan`. Declaring them here does not invent structure — it makes the structure
 * that existed only in prose into something a scanner can check, and something a NEW field can be
 * noticed against.
 */
export const LESSONS_SHAPE = {
  entryDepth: 3,
  fields: ["SHA", "DATE", "STATUS", "SIGNAL", "ROOT CAUSE", "PREVENTION", "SIDE QUESTS"],
};

/**
 * Contextual systems — SEEDED files, the second of the two file classes.
 *
 * The distinction this component exists for: the harness owns their SHAPE and must never own their
 * CONTENT. `SampleFile` writes the file once if it is absent and never touches it again, so a
 * repository's own lessons, ideas and backlog are permanently its own — regeneration cannot reach
 * them the way it reaches `biome.json`.
 *
 * What IS generated is the declaration: `harness-shape.json` says what structure each system has, so
 * `harness-shape-scan` can tell an added ENTRY (content — invisible, none of our business) from an
 * added FIELD OR SECTION (shape — somebody extended the system itself, which is a promotion
 * candidate). That distinction is what makes "content stays local" a property of the code rather
 * than a promise nobody can check.
 */
export class ContextualSystemsComponent extends Component {
  constructor(project, options = {}) {
    super(project, "harness-contextual-systems");

    const systems = options.contextualSystems ?? {
      "docs/LESSONS.md": { schema: LESSONS_SHAPE, seed: template("common/docs/LESSONS.md") },
    };

    const declared = {};
    for (const [path, { schema, seed }] of Object.entries(systems)) {
      // SampleFile, never TextFile: this file's content belongs to the repository the moment it
      // exists. A regenerated LESSONS.md would delete the incidents it was created to remember.
      if (seed !== undefined) new SampleFile(project, path, { contents: seed });
      declared[path] = schema;
    }

    new JsonFile(project, "harness-shape.json", {
      obj: { systems: declared },
      marker: false,
      readonly: true,
    });
    // The script itself comes from GATE_SCRIPTS via GatesComponent — one definition, not two.
    project.addVerifyStep("npm run shape:scan");
  }
}

/** Directories inside the package that hold agent and skill markdown, in load order. */
const CLAUDE_SOURCES = ["../plugins/harness-core", "../plugins/harness-gates"];

/**
 * The drills and the athletes — agents and skills, delivered without a plugin marketplace.
 *
 * Claude Code discovers these in `.claude/agents/` and `.claude/skills/` and nowhere else. There is
 * no npm resolution for them, which is the one thing the marketplace did that a package cannot: a
 * plugin is copied into `~/.claude/plugins/cache` and found from there. So the package ships the
 * markdown and this writes it into the two directories that are actually read.
 *
 * GENERATED, not gitignored. The alternative was a derived copy excluded from git, and committed is
 * better on every axis that matters here: an adopter can read the drills their repo actually has,
 * diff them when the harness moves, and the anti-tamper check catches a hand edit instead of it being
 * silently reverted on the next install. The file says it is generated and where to change it.
 */
export class ClaudeComponent extends Component {
  constructor(project) {
    super(project, "harness-claude");

    for (const base of CLAUDE_SOURCES) {
      const agents = join(HERE, base, "agents");
      if (existsSync(agents)) {
        for (const f of readdirSync(agents).filter((n) => n.endsWith(".md"))) {
          new TextFile(project, `.claude/agents/${f}`, {
            lines: readFileSync(join(agents, f), "utf8").split("\n"),
            readonly: true,
            marker: false, // front-matter is parsed; a comment above it would not survive
          });
        }
      }

      const skills = join(HERE, base, "skills");
      if (!existsSync(skills)) continue;
      for (const name of readdirSync(skills)) {
        const src = join(skills, name, "SKILL.md");
        if (!existsSync(src)) continue;
        new TextFile(project, `.claude/skills/${name}/SKILL.md`, {
          lines: readFileSync(src, "utf8").split("\n"),
          readonly: true,
          marker: false,
        });
      }
    }
  }
}

/**
 * The git hooks — the local half of the gate, where a slip costs seconds instead of a CI round trip.
 *
 * `pre-push` runs the full verify on purpose: CI is confirmation, not the first line of defence. The
 * templates are read rather than restated, same as biome, so the bootstrap and synthesis paths cannot
 * drift while both exist.
 */
export class HooksComponent extends Component {
  constructor(project, options = {}) {
    super(project, "harness-hooks");
    for (const hook of ["pre-commit", "commit-msg", "pre-push", "post-commit"]) {
      new TextFile(project, `.husky/${hook}`, {
        lines: template(`husky/${hook}`).split("\n"),
        executable: true,
        readonly: true,
        marker: false, // these are shell scripts git executes; a projen marker line is not a comment it should carry
      });
    }
    project.addDevDeps(`husky@${options.huskyVersion ?? "^9.1.7"}`);
    // `prepare` is npm's own lifecycle hook — husky installs itself on every `npm install`.
    project.package.setScript("prepare", "husky");
  }
}

/**
 * This package's own version, so an emitted `uses:` pins the ref it was installed at.
 *
 * The committed value is a PLACEHOLDER — semantic-release writes the real number into the workspace
 * immediately before packing and never commits it back, so an installed copy carries the truth and a
 * git checkout does not. That is fine for the case that matters (a consumer installs from npm) and
 * dangerous for the case that does not: emitting `@v0.0.0-development` into somebody's CI would be a
 * ref that resolves to nothing, discovered on their first pull request rather than here.
 *
 * So it refuses. A synthesizer that cannot name its own version has no business pinning one, and
 * `harnessRef` is the deliberate override for anyone genuinely working from a checkout.
 */
const HARNESS_VERSION = JSON.parse(readFileSync(join(HERE, "../package.json"), "utf8")).version;
const VERSION_IS_PLACEHOLDER = HARNESS_VERSION.startsWith("0.0.0-");

function pinnedRef(explicit) {
  if (explicit) return explicit;
  if (VERSION_IS_PLACEHOLDER) {
    throw new Error(
      `cannot pin a harness ref: this copy reports version "${HARNESS_VERSION}", which is the ` +
        "placeholder a git checkout carries rather than a published version. Install " +
        `${HARNESS_PACKAGE} from npm, or pass harnessRef explicitly.`,
    );
  }
  return `v${HARNESS_VERSION}`;
}

/**
 * The pipeline, CALLED rather than copied.
 *
 * The adopter's workflow is ten lines that invoke the harness's reusable one, and the shape is
 * deliberate. `preflight` in this repository refuses workflow edits to every principal including the
 * owner, because that file decides what runs with a repository's credentials — so an updater that
 * rewrote an adopter's CI would be the harness doing, in someone else's repo, the exact thing it
 * forbids everyone from doing in their own (idea #30).
 *
 * Inverting it fixes that by construction: the adopter owns their file, they pinned the ref, and the
 * ref is IMMUTABLE — a tag, never `@main`. Pointing at a moving branch would hand upstream the
 * ability to change what runs with their credentials at any time, which is the same hazard wearing a
 * convenience costume. Upgrading is a visible one-line diff they choose to take.
 */
export class WorkflowComponent extends Component {
  constructor(project, options = {}) {
    super(project, "harness-workflow");
    const ref = pinnedRef(options.harnessRef);

    new TextFile(project, ".github/workflows/verify.yml", {
      readonly: true,
      marker: false, // YAML takes comments, but the file carries its own provenance line below
      lines: [
        "# Generated by the harness — edit .projenrc.ts, not this file.",
        "#",
        "# The pipeline itself lives upstream and is CALLED, so improvements to it reach this repo",
        `# without anything rewriting this file. The ref is pinned on purpose: '@main' would let`,
        "# upstream change what runs with this repository's credentials at any time.",
        "name: verify",
        "",
        "on:",
        "  pull_request:",
        "    branches: [ main ]",
        "",
        "concurrency:",
        "  group: verify-${{ github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
        "  verify:",
        `    uses: ejclark/dungeon-crawler/.github/workflows/verify.yml@${ref}`,
        "",
      ],
    });
  }
}

/**
 * A container image, based on the harness's published one.
 *
 * `FROM` is the same delegation as `extends` and `uses:` — the base moves, the consumer's one line
 * does not. Kept minimal on purpose: a Dockerfile that guesses a build command produces an image
 * that fails at run time for a project shaped differently, which is the copy-a-template failure this
 * whole effort exists to stop.
 */
export class DockerComponent extends Component {
  constructor(project, options = {}) {
    super(project, "harness-docker");
    const base = options.dockerBase ?? `ghcr.io/ejclark/dungeon-crawler/node-base:${pinnedRef(options.harnessRef).slice(1)}`;

    new TextFile(project, "Dockerfile", {
      readonly: true,
      marker: false,
      lines: [
        "# Generated by the harness — edit .projenrc.ts, not this file.",
        `FROM ${base}`,
        "",
        "WORKDIR /app",
        "",
        "# Manifests first, so a source-only change does not invalidate the dependency layer.",
        "COPY package.json package-lock.json ./",
        "RUN npm ci --omit=dev",
        "",
        "COPY . .",
        "",
        "# Never root. A container that does not need write access to its own image should not have it.",
        "USER node",
        "",
      ],
    });
    new TextFile(project, ".dockerignore", {
      readonly: true,
      marker: false,
      lines: ["node_modules", ".git", ".github", "*.log", "", "# Never bake secrets into a layer.", ".env", ".env.*", ""],
    });
  }
}

/**
 * Sanitation — the tiers that make "extensible" and "principled" stop being opposites.
 *
 * The override API is unrestricted by design, which is what makes projen usable and also exactly how
 * weak config creeps in: any consumer can turn any rule off and synthesis will emit the weaker file
 * forever, quietly. Three tiers fix that without dictating — LOCKED cannot be weakened, RATCHETED may
 * be tightened but never loosened, and everything else is FREE.
 *
 * LOCKED is enforced HERE, during synthesis, because `postSynthesize` is the only point that sees the
 * final rendered state — after every `addOverride` a consumer applied. Catching it later, in CI, would
 * mean the weak config already exists on disk and somebody has already run against it.
 *
 * RATCHETED is enforced by `harness-sanitation` in the test suite instead, because it needs a budget
 * file and an `--update` path, and because it must GRANDFATHER: a repository whose config is weaker
 * than the harness would write gets today's number frozen as its baseline rather than a red build on
 * day one. A config gate is the easiest of all to switch off, and one that opens by condemning
 * shipped work gets switched off before it prevents anything.
 */
export class SanitationComponent extends Component {
  constructor(project) {
    super(project, "harness-sanitation");
    project.addVerifyStep("npm run sanitation");
  }

  postSynthesize() {
    const violations = lockedViolations(this.project.outdir);
    if (!violations.length) return;

    const lines = violations.map(
      (v) => `  ✗ ${v.file} → ${v.path} is ${JSON.stringify(v.actual)}, must be ${JSON.stringify(v.expect)}\n     ${v.why}`,
    );
    // Loud and specific. A refusal that does not say WHICH principle and WHY reads as the tool being
    // broken, and the next move is to delete the tool. If one of these is genuinely wrong for a real
    // repository, that is evidence about the PRINCIPLE — promote it upstream rather than route around
    // it, because routing around it is what this tier exists to make impossible.
    throw new Error(`sanitation refused this configuration:\n\n${lines.join("\n")}\n`);
  }
}

/**
 * A repository running the harness.
 *
 * Every `false` below is a measurement, not a preference — see the header and `docs/adr/0001`.
 */
export class HarnessProject extends typescript.TypeScriptProject {
  constructor(options) {
    super({
      // The consumer's release tooling owns its version; projen overwrites it otherwise.
      release: false,
      // We bring biome and rstest. Leaving these on installs a second linter and a second test runner.
      eslint: false,
      jest: false,
      prettier: false,
      ...options,
    });

    this.descriptor = Object.fromEntries(
      DESCRIPTOR_KEYS.map((k) => [k, options[k] ?? DEFAULTS[k]]),
    );

    // VERIFY NAMES ONLY THE CHECKS THAT EXIST.
    //
    // `configs.mjs` records this lesson at one layer down, learned twice: `--auto` wrote
    // `tsc -p tsconfig.json --noEmit` into a repository with no tsconfig, and the adopter's FIRST
    // verify failed on a file they did not have, in a script the harness had just written them.
    // The rule generalises past `sourceExt` — do not emit a command whose config does not exist — so
    // each component contributes its own step and `verify` is composed from what is actually here.
    // The other failure mode is a verify that passes because it stopped checking, which is why the
    // steps are collected rather than guessed.
    this.verifySteps = [];

    if (this.descriptor.sourceExt === ".ts") {
      // Safe to assert unconditionally: TypeScriptProject always writes a tsconfig.json, so unlike
      // the bootstrap path there is no repository shape where this command has no config to read.
      this.package.setScript("typecheck", "tsc -p tsconfig.json --noEmit");
      this.addVerifyStep("npm run typecheck");
    }

    new BiomeComponent(this, options);
    new RstestComponent(this, options);
    new GatesComponent(this, options);
    new ContextualSystemsComponent(this, options);
    new ClaudeComponent(this);
    new HooksComponent(this, options);
    if (options.workflow !== false) new WorkflowComponent(this, options);
    if (options.docker) new DockerComponent(this, options);
    new SanitationComponent(this);
  }

  /** Register a command that `verify` must run. Order is registration order; each must exit non-zero on failure. */
  addVerifyStep(step) {
    this.verifySteps.push(step);
  }

  preSynthesize() {
    super.preSynthesize();
    // Chained with `&&`, never piped. A pipeline exits with the LAST command's status, so
    // `check | tail` reports success for a failing check — the trap skynet's ENGINEERING.md names
    // and the reason this is composed here rather than left to a consumer to assemble.
    this.package.setScript("verify", this.verifySteps.join(" && "));
  }
}
