// THE SYNTHESIZER — a projen project type that writes the harness into a consuming repository.
//
// WHY projen AT ALL, given the bootstrap already writes these files. Because the bootstrap writes them
// exactly once. `put()` skips any file that exists, which is right for a file somebody customised and
// wrong for one that is merely old, and nothing can tell those apart (idea #29). projen deletes the
// question rather than answering it: you never customise the artifact, you customise the generator, and
// regeneration is the update path.
//
// WHAT WE TAKE FROM IT, AND WHAT WE REFUSE.
//
// Taken: the synthesis engine, component inheritance, and the override API.
//
// Refused, and measured rather than assumed (docs/adr/0001):
//   · THE TASK RUNNER. Routing scripts through projen Tasks costs +590ms on EVERY command — 456ms for
//     `biome check` becomes 1043ms — a constant tax that is 2.3x on a fast lint and lands squarely on
//     the inner loop. Writing the real command into package.json instead measured 263ms. So components
//     emit plain npm scripts, and package.json stays readable as itself.
//   · THE BATTERIES. TypeScriptProject ships jest, eslint and prettier. Adopting them would move a
//     consumer OFF biome and rstest, reversing the toolchain and trading one dependency for two.
//   · THE RELEASE. projen wrote `version: 0.0.0` over a real 1.129.0 until `release: false`. The
//     consumer's semantic-release owns its version; we do not.
//
// TWO FILE CLASSES, and the distinction is the whole shape/content split:
//   · GENERATED — rewritten every synth, content belongs upstream. `harness.json` is one.
//   · SEEDED — written once, NEVER clobbered, content belongs to the repo. Budgets, IDEAS.md,
//     LESSONS.md. The harness owns their SHAPE and validates it; it must never own what is in them.
import { Component, JsonFile, typescript } from "projen";
import { DEFAULTS } from "../plugins/harness-gates/lib/descriptor.mjs";

/** The npm package a consuming repository installs to get the gates on `node_modules/.bin`. */
export const HARNESS_PACKAGE = "@ejclark/dungeon-crawler";

/** Descriptor keys a consumer may set. Anything absent takes the documented default — never inference. */
const DESCRIPTOR_KEYS = Object.keys(DEFAULTS);

/**
 * The gate scripts, as PLAIN npm scripts pointing at `node_modules/.bin`.
 *
 * Not projen Tasks — see the header. And not `npx harness-…` either: `npx` re-resolves the package on
 * every invocation, which is a network round trip on a cold cache and another ~600ms when it is warm.
 * The bin is already on PATH inside an npm script, so the bare name is both the fastest form and the
 * one that fails loudly if the dependency is missing rather than silently fetching something.
 */
export const GATE_SCRIPTS = {
  "arch:scan": "harness-arch-scan",
  "dupe:scan": "harness-dupe-scan",
  "clone:scan": "harness-clone-scan",
  "dead:scan": "harness-dead-scan",
  "spec:gap": "harness-spec-gap-scan",
  "incident:scan": "harness-incident-scan",
};

/**
 * Emits `harness.json` — the capability descriptor every scanner reads.
 *
 * ONLY NON-DEFAULT KEYS ARE WRITTEN, and no file at all when a repo is entirely conventional. That is
 * `DESCRIPTOR.md`'s promise kept ("a conventional TypeScript project needs no file at all") rather than
 * restated: a descriptor listing six values identical to the defaults reads like six decisions somebody
 * made, and the next person to change a default would have to hunt them all down.
 *
 * This is a GENERATED file. It exists because the same values already live in `.projenrc.ts`, and two
 * hand-maintained copies of one truth is the drift this repository has a suite devoted to preventing.
 */
export class GatesComponent extends Component {
  constructor(project, options = {}) {
    super(project, "harness-gates");

    const declared = Object.fromEntries(
      DESCRIPTOR_KEYS.filter((k) => options[k] !== undefined && !same(options[k], DEFAULTS[k])).map((k) => [
        k,
        options[k],
      ]),
    );

    if (Object.keys(declared).length > 0) {
      new JsonFile(project, "harness.json", {
        obj: declared,
        marker: false, // a JSON descriptor read by six scanners; a "generated by" key is not schema
        readonly: true,
      });
    }

    project.addDevDeps(HARNESS_PACKAGE);
    for (const [name, exec] of Object.entries(GATE_SCRIPTS)) {
      project.package.setScript(name, exec);
    }
  }
}

/** Structural equality, good enough for descriptor values (strings and flat string arrays). */
function same(a, b) {
  return JSON.stringify(a) === JSON.stringify(b);
}

/**
 * A repository running the harness.
 *
 * Every `false` below is a measurement, not a preference — see the header and `docs/adr/0001`.
 */
export class HarnessProject extends typescript.TypeScriptProject {
  constructor(options) {
    super({
      // The consumer's release tooling owns its version; projen overwrites it otherwise.
      release: false,
      // We bring biome and rstest. Leaving these on installs a second linter and a second test runner.
      eslint: false,
      jest: false,
      prettier: false,
      ...options,
    });

    this.descriptor = Object.fromEntries(
      DESCRIPTOR_KEYS.map((k) => [k, options[k] ?? DEFAULTS[k]]),
    );

    new GatesComponent(this, options);
  }
}
