// THE VANILLA INTEGRATION — the harness's skills and agents as ordinary files in a target repo.
//
//   harness-claude-sync            # write .claude/agents/* and .claude/skills/* into this repo
//   harness-claude-sync --check    # exit 1 if any copy is missing or has drifted
//   harness-claude-sync --dry-run  # say what would change, write nothing
//
// WHY COPIES AT ALL, when a plugin marketplace already ships these. Because `/plugin install` is a
// step somebody has to have taken, and until they have, the repository looks empty: you open a
// checkout that AUTHORS ten agents and Claude Code offers you none of them, because plugin
// components only resolve for an installed plugin. A file in `.claude/agents/` needs no install, no
// marketplace, and no `CLAUDE_PLUGIN_ROOT` — it is visible in the tree, greppable, and reviewable in
// the diff of the pull request that changed it.
//
// AND WHY THAT IS NORMALLY A MISTAKE. Copies drift, and this project has the measurement rather than
// the worry: the agents were hand-copied into one repository once, and its `decomposer` is now
// eleven lines behind — it never learned that an athlete may not raise its own budget, and it still
// invokes a vendored scanner path the harness stopped using. Nobody was careless. A copy with no
// mechanism keeping it current only ever gets more wrong.
//
// SO: GENERATED, NEVER HAND-WRITTEN — the rule `sync-launchers.mjs` already runs on for the Windows
// `.cmd` twins, applied to the same problem one level up. A copy that a gate re-derives is an
// ARTIFACT, not a second instance, and the one-instance rule survives: the harness stays the single
// source, the target carries build output, and `--check` fails the moment the two disagree.
//
// The banner is what makes the promise checkable. It names the source and forbids local edits, so a
// person who improves an agent here improves it in the harness rather than in one repository's copy.
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

/** Comment syntax differs, so the banner does too. Markdown is all we ship today; keep it honest. */
const BANNER = (source) =>
  `<!-- GENERATED by harness-claude-sync from ${source} — edit that, not this.\n` +
  `     A local edit here is lost on the next sync and drifts this repo from the harness. -->\n`;

/**
 * Every skill and agent the installed plugins carry, as `{ dest, source, body }`.
 *
 * Walks `plugins/<plugin>/{skills,agents}` rather than taking a list, for the reason the launcher
 * sync gives: a list is a second place to remember something, and the entry that is missing is
 * invisible until somebody needs exactly that agent.
 */
export function claudeAssets(harnessRoot) {
  const out = [];
  const plugins = join(harnessRoot, "plugins");
  if (!existsSync(plugins)) return out;

  for (const plugin of readdirSync(plugins).sort()) {
    // Agents are single files; skills are directories that may carry references alongside SKILL.md.
    const agents = join(plugins, plugin, "agents");
    if (existsSync(agents)) {
      for (const name of readdirSync(agents).sort().filter((n) => n.endsWith(".md"))) {
        out.push({ dest: join(".claude/agents", name), source: `plugins/${plugin}/agents/${name}`, abs: join(agents, name) });
      }
    }

    const skills = join(plugins, plugin, "skills");
    if (!existsSync(skills)) continue;
    for (const skill of readdirSync(skills).sort()) {
      const dir = join(skills, skill);
      if (!statSync(dir).isDirectory()) continue;
      // `recursive` rather than a hand-rolled walk: the duplication gate caught this file defining
      // a third copy of a tree walk that already exists twice here. Node has done it since 20.
      for (const e of readdirSync(dir, { recursive: true, withFileTypes: true })) {
        if (e.isDirectory()) continue;
        const abs = join(e.parentPath ?? e.path, e.name);
        const within = relative(dir, abs).split("\\").join("/");
        out.push({ dest: join(".claude/skills", skill, within), source: `plugins/${plugin}/skills/${skill}/${within}`, abs });
      }
    }
  }
  return out;
}

/**
 * What the file should contain — the source, with a banner on any markdown that carries front matter.
 *
 * The banner goes AFTER the front matter, never before it. Claude Code parses `---` at byte zero;
 * a comment above it makes the block invisible and the skill loses its name and description, which
 * is a failure that looks like the skill simply not existing.
 */
export function bodyFor({ abs, source }) {
  const raw = readFileSync(abs, "utf8");
  if (!source.endsWith(".md")) return raw;
  const m = raw.match(/^---\n[\s\S]*?\n---\n/);
  return m ? `${m[0]}${BANNER(source)}${raw.slice(m[0].length)}` : `${BANNER(source)}${raw}`;
}

/**
 * Sync into `targetRoot`. Returns what changed and what drifted, and writes nothing in check mode.
 *
 * DRIFT IS A FILE THAT EXISTS AND DISAGREES, which is the case worth separating from a file that is
 * merely absent: absent is a repo that has not synced yet, and disagreeing is a repo where somebody
 * edited the artifact instead of the source. The first is routine; the second is the failure this
 * whole mechanism exists to make impossible, and reporting them the same way would hide it.
 */
export function syncClaudeAssets(harnessRoot, targetRoot, { check = false, dryRun = false } = {}) {
  const wrote = [];
  const drifted = [];
  const missing = [];

  for (const asset of claudeAssets(harnessRoot)) {
    const dest = join(targetRoot, asset.dest);
    const want = bodyFor(asset);
    const have = existsSync(dest) ? readFileSync(dest, "utf8") : null;
    if (have === want) continue;

    (have === null ? missing : drifted).push(asset.dest);
    if (check || dryRun) continue;
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, want);
    wrote.push(asset.dest);
  }
  return { wrote, drifted, missing };
}

/**
 * Hand every asset to a `put(dest, body)` — the shape `harness-bootstrap` already uses for its files.
 *
 * Here rather than inline in the bootstrap so that adopting the drills costs the bootstrap one line
 * instead of a loop plus the paragraph explaining it. The bootstrap's job is the sequence; what a
 * generated `.claude/` file is remains this module's business.
 */
export function installClaudeAssets(harnessRoot, put) {
  for (const asset of claudeAssets(harnessRoot)) put(asset.dest, bodyFor(asset));
}
